modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "drop_confirm"
version = "${version}"
displayName = "DropConfirm"
authors = "pupbrained"
description = '''
Think twice before you drop.
'''
#logoFile = ""

[[dependencies.drop_confirm]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drop_confirm]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "drop_confirm.mixins.json"