modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "drop_confirm"
version = "${mod_version}"
displayName = "DropConfirm"
authors = "pupbrained"
description = '''
Think twice before you drop.
'''
logoFile = "icon.png"

[[dependencies.drop_confirm]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drop_confirm]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drop_confirm]]
modId = "architectury"
type = "required"
versionRange = "[11.0.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drop_confirm]]
modId = "the_config_lib"
type = "required"
versionRange = "[4.0.0-SNAPSHOT,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "drop_confirm-common.mixins.json"
